repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
        files: \.toml$
      - id: check-yaml
        files: \.yaml$
      - id: end-of-file-fixer
        files: \.py$
      - id: mixed-line-ending
        files: \.py$
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        files: \.py$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]